services:
  backend:
    image: api-mrgrd56
    build:
      context: .
      args:
        APP_NAME: api-mrgrd56
    ports:
      - "8080:8080"
    restart: always
    environment:
      ENV: production
      NODE_ENV: production
      SPRING_PROFILES_ACTIVE: prod
      TESSDATA_PREFIX: /usr/share/tesseract-ocr/5/
    extra_hosts:
      - "host.docker.internal:host-gateway"