spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration