server:
  port: 8080

spring:
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  jackson:
    serialization:
      write-dates-as-timestamps: false

tesseract:
  datapath: C:\Program Files\Tesseract-OCR\tessdata